=== JTOne123/PdfCardGenerator/PdfGenerator/XMLImport.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="XMLSchema1"
    targetNamespace="http://tempuri.org/PDFGenerator"
    elementFormDefault="qualified"
    xmlns="http://tempuri.org/PDFGenerator"
    xmlns:mstns="http://tempuri.org/PDFGenerator"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:element name="Project">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Template" maxOccurs="unbounded">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded">
              <xs:element name="Image" type="mstns:ImageElement" />
              <xs:element name="Text" type="mstns:TextElement" />
            </xs:choice>
            <xs:attribute name="Context" type="xs:string"/>
            <xs:attribute name="Width" type="mstns:Unit"/>
            <xs:attribute name="Height" type="mstns:Unit"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!--<xs:attributeGroup name="VisibleGroup">
    <xs:attribute name="IsVisible" type="xs:boolean"/>
    <xs:attribute name="IsVisiblePath" type="xs:string"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="WordStyleGroup">
    <xs:attributeGroup ref="mstns:VisibleGroup" />
    <xs:attribute name="FontStyle" type="mstns:FontStyle"/>
    <xs:attribute name="EmSize" type="xs:double"/>
    <xs:attribute name="FontName" type="xs:string"/>

    <xs:attribute name="FontStylePath" type="xs:string"/>
    <xs:attribute name="EmSizePath" type="xs:string"/>
    <xs:attribute name="FontNamePath" type="xs:string"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="ParagraphStyleGroup">
    <xs:attributeGroup ref="mstns:WordStyleGroup" />

    <xs:attribute name="Linespacing" default="1" type="xs:double"/>
    <xs:attribute name="BeforeParagraph" type="mstns:Unit"/>
    <xs:attribute name="AfterParagraph" type="mstns:Unit"/>

    <xs:attribute name="LinespacingPath" default="1" type="xs:string"/>
    <xs:attribute name="BeforeParagraphPath" type="xs:string"/>
    <xs:attribute name="AfterParagraphPath" type="xs:string"/>

  </xs:attributeGroup>-->

  <!--<xs:attributeGroup name="PositionGroup">
    <xs:attribute name="left" type="mstns:Unit"/>
    <xs:attribute name="top" type="mstns:Unit"/>
    <xs:attribute name="width" type="mstns:Unit"/>
    <xs:attribute name="height" type="mstns:Unit"/>
  </xs:attributeGroup>-->

  <xs:simpleType name="FontStyle">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Regular" />
      <xs:enumeration value="Bold" />
      <xs:enumeration value="Italic" />
      <xs:enumeration value="BoldItalic" />
      <xs:enumeration value="Underline" />
      <xs:enumeration value="Strikeout" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Alignment">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Near" />
      <xs:enumeration value="Center" />
      <xs:enumeration value="Far" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="Unit">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+(\.[0-9]+)? ?(pt|mm|cm|in|pu)"/>
    </xs:restriction>
  </xs:simpleType>


  <!--<xs:attributeGroup name="baseElementGroup">
    <xs:attributeGroup ref="VisibleGroup"/>
    <xs:attributeGroup ref="PositionGroup"/>
  </xs:attributeGroup>-->

  <!--<xs:complexType name="imageElement">
    <xs:attribute name="Path" type="xs:string"/>
    <xs:attributeGroup ref="mstns:baseElementGroup"/>
  </xs:complexType>-->

  <!--<xs:complexType name="textElement">
    <xs:sequence>
      <xs:element name="Paragraph" maxOccurs="unbounded">
        <xs:complexType>
          <xs:choice maxOccurs="unbounded">
            <xs:element name="LineBreak">
              <xs:complexType>
                <xs:attributeGroup ref="mstns:WordStyleGroup"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="Run">
              <xs:complexType >
                <xs:simpleContent>
                  <xs:extension base="xs:string">
                    <xs:attributeGroup ref="mstns:WordStyleGroup"/>
                  </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>
          </xs:choice>
          <xs:attributeGroup ref="mstns:ParagraphStyleGroup"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attributeGroup ref="mstns:baseElementGroup"/>
  </xs:complexType>-->


  <xs:complexType name="BaseElement" abstract="true">

    <xs:attribute name="left" type="mstns:Unit"/>
    <xs:attribute name="top" type="mstns:Unit"/>
    <xs:attribute name="width" type="mstns:Unit"/>
    <xs:attribute name="height" type="mstns:Unit"/>

    <xs:attribute name="IsVisible" type="xs:boolean"/>
    <xs:attribute name="IsVisiblePath" type="xs:string"/>

    <xs:attribute name="ZPosition" type="xs:double"/>


  </xs:complexType>
  
  <xs:complexType name="TextElement">
    <xs:complexContent>
      <xs:extension base="BaseElement">
        <xs:sequence>
          <xs:element name="Paragraph" maxOccurs="unbounded">
            <xs:complexType>
              <xs:choice maxOccurs="unbounded">
                <xs:element name="LineBreak" type="LineBreak"/>
                <xs:element name="Run" type="TextRun" />
              </xs:choice>


              <xs:attribute name="IsVisible" type="xs:boolean"/>
              <xs:attribute name="IsVisiblePath" type="xs:string"/>

              <xs:attribute name="FontStyle" type="mstns:FontStyle"/>
              <xs:attribute name="EmSize" type="xs:double"/>
              <xs:attribute name="FontName" type="xs:string"/>

              <xs:attribute name="Linespacing" default="1" type="xs:double"/>
              <xs:attribute name="BeforeParagraph" type="mstns:Unit"/>
              <xs:attribute name="AfterParagraph" type="mstns:Unit"/>
              <xs:attribute name="Alignment" type="mstns:Alignment"/>

            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>


  <xs:complexType name="LineBreak">
    <xs:complexContent>
      <xs:extension base="Run">

      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="TextRun">
    <xs:complexContent>
      <xs:extension base="Run">
        <xs:choice>
          <xs:element  name="Text" type="xs:string"/>
          <xs:element  name="TextPath" type="xs:string"/>
        </xs:choice>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Run" abstract="true">
    
      <xs:attribute name="FontStyle" type="mstns:FontStyle"/>
      <xs:attribute name="EmSize" type="xs:double"/>
      <xs:attribute name="FontName" type="xs:string"/>

    <xs:attribute name="IsVisible" type="xs:boolean"/>
    <xs:attribute name="IsVisiblePath" type="xs:string"/>
    
  </xs:complexType>

  <xs:complexType name="ImageElement">
    <xs:complexContent>
      <xs:extension base="BaseElement">
        <xs:attribute name="ImageLocationPath" type="xs:string"/>
        <xs:attribute name="ImageLocation" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  
</xs:schema>

=== JTOne123/PdfCardGenerator/PDFGeneratorClient/Project.xml
<!-- This sample uses nota.xml from https://github.com/nota-game/nota -->
<!-- If you need xml namespaces in the xpath querys, you need to define those in the project root-->
<Project xmlns="https://raw.githubusercontent.com/LokiMidgard/PdfGenerator/master/PdfGenerator/XMLImport.xsd"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:nota='http://nota.org/schema/nota'
  xmlns:misc='http://nota.org/schema/misc'
  xmlns:lebewesen="http://nota.org/schema/wesen"
  xmlns:kultur="http://nota.org/schema/kultur"
  xmlns:profession="http://nota.org/schema/profession"
  xmlns:talent="http://nota.org/schema/talent"
  xmlns:fertigkeit="http://nota.org/schema/fertigkeit"
  xmlns:besonderheit="http://nota.org/schema/besonderheit"
  xmlns:aktionen="http://nota.org/schema/kampf/aktionen"
  xmlns:ausstattung="http://nota.org/schema/kampf/ausstattung"
         xsi:schemaLocation="https://raw.githubusercontent.com/LokiMidgard/PdfGenerator/master/PdfGenerator/XMLImport.xsd ../PDFGenerator/XMLImport.xsd">
  <Template Context="//nota:Daten/aktionen:Aktionen/*" Width="63 mm" Height="88 mm">
    <Text left="9 mm" top="3mm" width="43 mm" height="8mm">
      <Paragraph  Alignment="Center" EmSize="12" FontStyle="Bold">
        <Run>
          <TextPath>@Name</TextPath>
        </Run>
      </Paragraph>
    </Text>

    <Image left="52 mm" top="3 mm" width="6 mm" height="8 mm" ImageLocation="Flamme.png" IsVisible="true" />

    <Text left="3 mm" top="3 mm" width="6 mm" height="8 mm">
      <Paragraph  Alignment="Center" EmSize="7">
        <Run>
          <TextPath>@Kosten</TextPath>
        </Run>
      </Paragraph>
    </Text>


    <Text left="3mm" top="70 mm" width="55mm" height="6 mm" >
      <Paragraph FontStyle="Italic" EmSize="7">
        <Run>
          <TextPath>./aktionen:Beschreibung</TextPath>
        </Run>
      </Paragraph>
    </Text>
    <Text left="3mm" top="76 mm" width="55 mm" height="6.3 mm" >
      <Paragraph FontStyle="Italic" EmSize="7">
        <Run>
          <TextPath>./aktionen:Beschreibung</TextPath>
        </Run>
      </Paragraph>
    </Text>

    <Text left="3 mm" top="11 mm" width="55mm" height="58.1mm" >
      <Paragraph FontStyle="Italic" EmSize="7" IsVisiblePath="./aktionen:Beschreibung">
        <Run>
          <TextPath>./aktionen:Beschreibung</TextPath>
        </Run>
      </Paragraph>

      <Paragraph IsVisiblePath="./aktionen:Bedingung" BeforeParagraph="4mm" AfterParagraph="2mm" FontStyle="Bold" EmSize="8">
        <Run>
          <Text>Bedingung</Text>
        </Run>
      </Paragraph>
      <Paragraph IsVisiblePath="./aktionen:Bedingung" BeforeParagraph="1mm" AfterParagraph="0mm" EmSize="7">
        <Run>
          <TextPath>./aktionen:Bedingung</TextPath>
        </Run>
      </Paragraph>

      <Paragraph IsVisiblePath="./aktionen:InstantEffektBedingung" BeforeParagraph="4mm" AfterParagraph="2mm" FontStyle="Bold" EmSize="8">
        <Run>
          <Text>Augenblicklicher Effekt</Text>
        </Run>
      </Paragraph>
      <Paragraph IsVisiblePath="./aktionen:InstantEffekt" BeforeParagraph="1mm" AfterParagraph="0mm" EmSize="7">
        <Run>
          <TextPath>./aktionen:InstantEffekt</TextPath>
        </Run>
      </Paragraph>

      <Paragraph IsVisiblePath="./aktionen:GarantierterEffekt" BeforeParagraph="4mm" AfterParagraph="2mm" FontStyle="Bold" EmSize="8">
        <Run>
          <Text>Garantierter Effekt</Text>
        </Run>
      </Paragraph>
      <Paragraph IsVisiblePath="./aktionen:GarantierterEffekt" BeforeParagraph="1mm" AfterParagraph="0mm" EmSize="7">
        <Run>
          <TextPath>./aktionen:GarantierterEffekt</TextPath>
        </Run>
      </Paragraph>

      <Paragraph IsVisiblePath="./aktionen:OffensivErfolg" BeforeParagraph="4mm" AfterParagraph="2mm" FontStyle="Bold" EmSize="8">
        <Run>
          <Text>Offensiv Erfolg</Text>
        </Run>
      </Paragraph>
      <Paragraph IsVisiblePath="./aktionen:OffensivErfolg" BeforeParagraph="1mm" AfterParagraph="0mm" EmSize="7">
        <Run>
          <TextPath>./aktionen:OffensivErfolg</TextPath>
        </Run>
      </Paragraph>

      <Paragraph IsVisiblePath="./aktionen:DefensivErfolg" BeforeParagraph="4mm" AfterParagraph="2mm" FontStyle="Bold" EmSize="8">
        <Run>
          <Text>Defensiver Erfolg</Text>
        </Run>
      </Paragraph>
      <Paragraph IsVisiblePath="./aktionen:DefensivErfolg" BeforeParagraph="1mm" AfterParagraph="0mm" EmSize="7">
        <Run>
          <TextPath>./aktionen:DefensivErfolg</TextPath>
        </Run>
      </Paragraph>

      <Paragraph IsVisiblePath="./aktionen:SekundärErfolg" BeforeParagraph="4mm" AfterParagraph="2mm" FontStyle="Bold" EmSize="8">
        <Run>
          <Text>Sekundeärer Erfolg</Text>
        </Run>
      </Paragraph>
      <Paragraph IsVisiblePath="./aktionen:SekundärErfolg" BeforeParagraph="1mm" AfterParagraph="0mm" EmSize="7">
        <Run>
          <TextPath>./aktionen:SekundärErfolg</TextPath>
        </Run>
      </Paragraph>

      <Paragraph IsVisiblePath="./aktionen:OffensivMiserfolg" BeforeParagraph="4mm" AfterParagraph="2mm" FontStyle="Bold" EmSize="8">
        <Run>
          <Text>Offensiver Misserfolg</Text>
        </Run>
      </Paragraph>
      <Paragraph IsVisiblePath="./aktionen:OffensivMiserfolg" BeforeParagraph="1mm" AfterParagraph="0mm" EmSize="7">
        <Run>
          <TextPath>./aktionen:OffensivMiserfolg</TextPath>
        </Run>
      </Paragraph>

      <Paragraph IsVisiblePath="./aktionen:DefensivMiserfolg" BeforeParagraph="4mm" AfterParagraph="2mm" FontStyle="Bold" EmSize="8">
        <Run>
          <Text>Defensiver Misserfolg</Text>
        </Run>
      </Paragraph>
      <Paragraph IsVisiblePath="./aktionen:DefensivMiserfolg" BeforeParagraph="1mm" AfterParagraph="0mm" EmSize="7">
        <Run>
          <TextPath>./aktionen:DefensivMiserfolg</TextPath>
        </Run>
      </Paragraph>


      <Paragraph IsVisiblePath="./aktionen:SekundärMiserfolg" BeforeParagraph="4mm" AfterParagraph="2mm" FontStyle="Bold" EmSize="8">
        <Run>
          <Text>Säkundärer Misserfolg</Text>
        </Run>
      </Paragraph>
      <Paragraph IsVisiblePath="./aktionen:SekundärMiserfolg" BeforeParagraph="1mm" AfterParagraph="0mm" EmSize="7">
        <Run>
          <TextPath>./aktionen:SekundärMiserfolg</TextPath>
        </Run>
      </Paragraph>



    </Text>


  </Template>


</Project>
